name = "rak-tv-worker"
main = "index.js"
compatibility_date = "2024-01-01"
workers_dev = true

[[kv_namespaces]]
binding = "RAK_KV"
id = "bf17011ba25a46d9bf8937d9e96fde38"
preview_id = "bf17011ba25a46d9bf8937d9e96fde38"

[vars]
ALLOWED_ORIGIN = "https://your-site.vercel.app"
